language: python

matrix:
  include:
    - os: linux
      env:
        - LUA="lua=5.3"
cache:
  directories:
    - hrenv

before_install:
  - pip install hererocks
  - hererocks hrenv -rlatest --$LUA
  - source hrenv/bin/activate

install:
  - luarocks install busted
  - luarocks install luacheck
  - luarocks make # This installs necessary runtime dependencies

before_script:
  - make linux-noreadline

script:
  - busted -o gtest -v ./spec
  - luacheck ./pallene ./spec


